apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    run: exploit
  name: exploit
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: exploit
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: exploit
      name: exploit    
    spec:
      containers:
      - args:
        - bash
        image: horantj/exploit:8
        imagePullPolicy: IfNotPresent
        name: exploit
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30