struts:
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: false
    host: "struts.host"
    ingressClassName: ""
    path: "/"
    annotations: {}
    tls: true
exploit:
  image_tag: "0.4"